Repository Bhuvana102/Good-Reads, pull requests merged in 2022-04, with the labels that each got.

#109 Post Review UI Changes
  WebApp/src/app/book-details/book-details.component.html
  WebApp/src/app/book-details/book-details.component.scss
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/genre-books/genre-books.component.ts
  WebApp/src/app/models/general-models.ts
  WebApp/src/app/services/api.service.ts
Labels: Feature, Sprint 3

#112 Posting a review to backend
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/services/api.service.ts
  backend/controller/addReviewsHandler.go
  backend/databases/books.db
Labels: Feature, Sprint 3

#115 Basic Design for Review View
  WebApp/src/app/app.module.ts
  WebApp/src/app/book-details/book-details.component.scss
  WebApp/src/app/book-reviews/book-reviews.component.html
  WebApp/src/app/book-reviews/book-reviews.component.scss
  WebApp/src/app/book-reviews/book-reviews.component.ts
  backend/databases/books.db
Labels: Feature, Sprint 3

#121 Accessed Proper API Response
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/services/api.service.ts
  backend/controller/addReviewsHandler.go
  backend/databases/books.db
Labels: enhancement, Sprint 3

#122 UI Fix for overlapping components
  WebApp/src/app/book-attributes/book-attributes.component.html
  WebApp/src/app/book-attributes/book-attributes.component.scss
  WebApp/src/app/book-details/book-details.component.scss
Labels: enhancement, Sprint 3

#123 Update The number of Ratings and number of Reviews in Books DB On Adding new Reviews
  backend/model/addReviewFunc.go
Labels: enhancement, Feature, Sprint 3

#128 Test case for Fetch book ratings api
  backend/testing/testGetRatings_test.go
Labels: Testing, Sprint 3

#130 Test Case for Retrieve Reviews
  backend/testing/testRetrieveReviews_test.go
Labels: Testing, Sprint 3

#134 Test Cases for testAddReviews_test.go
  backend/testing/testAddReviews_test.go
Labels: Testing, Sprint 3

#135 Updating average rating, no of ratings and no of reviews columns of b…
  backend/model/addReviewFunc.go
Labels: enhancement, Sprint 3

#136 Added dynamic reviews and dynamic rating
  WebApp/src/app/book-attributes/book-attributes.component.html
  WebApp/src/app/book-attributes/book-attributes.component.scss
  WebApp/src/app/book-attributes/book-attributes.component.ts
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/book-reviews/book-reviews.component.html
  WebApp/src/app/book-reviews/book-reviews.component.ts
  WebApp/src/app/models/general-models.ts
  WebApp/src/app/services/api.service.ts
  WebApp/src/app/services/global.service.ts
Labels: enhancement, Sprint 3

#138 Cypress test for Book-Details Page
  WebApp/cypress/integration/book-details.specs.ts
  WebApp/src/app/book-details/book-details.component.html
  WebApp/src/app/book-reviews/book-reviews.component.html
Labels: Testing, Sprint 3

#143 dynamic bug fix
  WebApp/src/app/book-attributes/book-attributes.component.html
  WebApp/src/app/book-attributes/book-attributes.component.ts
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/book-reviews/book-reviews.component.html
  WebApp/src/app/book-reviews/book-reviews.component.ts
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/services/global.service.ts
Labels: bug, Sprint 3 Bug

#147 Average Rating Update
  WebApp/src/app/book-attributes/book-attributes.component.html
  WebApp/src/app/book-attributes/book-attributes.component.scss
  WebApp/src/app/book-attributes/book-attributes.component.ts
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/book-reviews/book-reviews.component.scss
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/models/general-models.ts
Labels: Feature, Sprint 4

#148 controller to Fetch Top Rated Books For a given Genre ID
  backend/controller/fetchTopBooksForGenre.go
Labels: Feature, Sprint 4

#155 Update fetchTopBooksForGenreHandler.go
  backend/controller/fetchTopBooksForGenreHandler.go
Labels: bug resolution, Sprint 4

#158 Update fetchTopBooksForGenreHandler.go
  backend/testing/testfetchTopBooksForGenre_test.go
Labels: Testing, Sprint 4

#166 Added Validations to Login and Register
  WebApp/src/app/login/login.component.html
  WebApp/src/app/login/login.component.ts
  backend/databases/books.db
Labels: Feature, Sprint 4

#163 Route and struct for user registration api
  backend/controller/registerUserHandler.go
  backend/controller/route.go
  backend/model/connect.go
  backend/model/registerUserFunc.go
  backend/views/structs.go
Labels: Feature

#169 Created Fields In Register Page
  WebApp/src/app/login/login.component.html
Labels: Feature, Sprint 4

#170 Registration Logic Milestone
  WebApp/src/app/login/login.component.html
  WebApp/src/app/login/login.component.ts
  WebApp/src/app/services/api.service.ts
Labels: Feature, Sprint 4

#172 Fixing string and json return whenever api is called
  backend/controller/registerUserHandler.go
Labels: bug resolution, Sprint 4

#174 Posting User Registration Data
  WebApp/src/app/services/api.service.ts
  backend/controller/registerUserHandler.go
  backend/databases/books.db
Labels: Feature, Sprint 4

#175 Registration Final
  WebApp/src/app/login/login.component.ts
Labels: Feature, Sprint 4

#176 Api to authenticate users login attempt
  backend/controller/authenticateUserHandler.go
  backend/controller/route.go
  backend/model/AuthenticateUserFunc.go
  backend/views/structs.go
Labels: Feature, Sprint 4

#177 Login Authentication Milestone
  WebApp/src/app/login/login.component.ts
  WebApp/src/app/models/general-models.ts
  WebApp/src/app/services/api.service.ts
Labels: Feature, Sprint 4

#179 fixing CORS issue login authentication api
  backend/controller/authenticateUserHandler.go
Labels: bug

#180 Login Auth
  WebApp/src/app/login/login.component.ts
Labels: Feature, Sprint 4

#182 Updating CORS header policy for login api
  backend/controller/authenticateUserHandler.go
Labels: bug

#185 Login Auth
  WebApp/src/app/book-attributes/book-attributes.component.ts
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/login/login.component.ts
  WebApp/src/app/models/general-models.ts
  WebApp/src/app/services/api.service.ts
Labels: Feature, Sprint 4

#186 API to add books to Mybooks tagged to a user
  backend/controller/addMyBooksHandler.go
  backend/controller/route.go
  backend/model/addMyBooksFunc.go
  backend/model/connect.go
  backend/views/structs.go
Labels: Feature, Sprint 4

#188 Cypress Modifications
  WebApp/cypress/integration/book-details.spec.ts
  WebApp/cypress/integration/login.spec.ts
  WebApp/cypress/integration/page.spec.ts
  WebApp/src/app/book-attributes/book-attributes.component.html
  WebApp/src/app/book-attributes/book-attributes.component.ts
  WebApp/src/app/book-attributes/genre-books.component.html
  WebApp/src/app/book-details/book-details.component.ts
  WebApp/src/app/book-reviews/book-reviews.component.ts
  backend/databases/books.db
Labels: Sprint 4
