Repository Bhuvana102/Good-Reads, pull requests merged in 2022-03, with the labels that each got.

#72 Frontend login Validation
  WebApp/cypress.json
  WebApp/cypress/.eslintrc.json
  WebApp/cypress/fixtures/example.json
  WebApp/cypress/integration/login.specs.ts
  WebApp/cypress/plugins/index.js
  WebApp/cypress/support/commands.js
  WebApp/cypress/support/index.js
  WebApp/package-lock.json
  WebApp/package.json
  WebApp/src/app/app.module.ts
  WebApp/src/app/login/login.component.html
  WebApp/src/app/login/login.component.ts
  WebApp/tsconfig.app.json
  WebApp/tsconfig.json
  WebApp/tsconfig.spec.json
Labels: Feature, Sprint2

#74 Cypress Testing Login Feature
  WebApp/cypress/integration/login.specs.ts
  WebApp/src/app/login/login.component.html
Labels: Sprint2, Testing

#78 Creating An Api to Add Reviews to the Review Table
  backend/controller/addReviewsHandler.go
  backend/controller/route.go
  backend/model/addReviewFunc.go
Labels: Feature, Sprint2

#80 Modify the Genres table content
  backend/databases/books.db
  backend/model/connect.go
Labels: bug, Sprint1-Bugs, Sprint2

#85 Hover Bug Fix
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.ts
Labels: bug, Sprint1-Bugs, Sprint2, bug resolution

#86 Integration testing using Cypress
  WebApp/cypress/integration/page.spec.ts
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.spec.ts
Labels: Testing

#90 Added a delay in Cypress integration testing
  WebApp/cypress/integration/page.spec.ts
Labels: Testing

#92 Logout Feature
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.ts
Labels: Feature, Sprint2

#95 Create a test Api to Check if Genres are present in the database or n…
  backend/testing/testGetAllGenres_test.go
Labels: Sprint2, Testing

#98 Url change to Fetch the genre for a given genre ID
  backend/controller/fetchBookDataHandler.go
  backend/controller/fetchGenreBooksHandler.go
  backend/controller/getGenres.go
  backend/controller/retrieveReviewsHandler.go
  backend/controller/route.go
  backend/model/genres.go
Labels: enhancement, bug resolution, Sprint 2 bugs
