Repository Bhuvana102/Good-Reads, pull requests merged in 2022-02, with the labels that each got.

#14 Creating the various Genres in the database
  backend/databases/books.db
  backend/main.go
  backend/model/genres.go
  backend/views/structs.go
Labels: Sprint1, Feature

#21 API calls for the various genres of books
  .vscode/launch.json
  backend/databases/books.db
  backend/main.go
  backend/model/connect.go
  backend/model/genres.go
Labels: Sprint1, Feature

#23 Refactoring the code to fetch API from the controller
  backend/controller/route.go
  backend/main.go
Labels: enhancement, Sprint1, Feature

#27 Manish
  WebApp/angular.json
  WebApp/package-lock.json
  WebApp/package.json
  WebApp/src/app/app.module.ts
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.scss
  WebApp/src/app/common-menu/common-menu.component.spec.ts
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/common-menu/coomon-menu-routing.module.ts
  WebApp/src/app/community/community-routing.module.ts
  WebApp/src/app/community/community.component.html
  WebApp/src/app/community/community.component.scss
  WebApp/src/app/community/community.component.spec.ts
  WebApp/src/app/community/community.component.ts
  WebApp/src/app/homepage/homepage-routing.component.ts
  WebApp/src/app/homepage/homepage.component.html
  WebApp/src/app/homepage/homepage.component.scss
  WebApp/src/app/homepage/homepage.component.ts
  WebApp/src/app/login/login.component.html
  WebApp/src/app/login/login.component.scss
  WebApp/src/app/services/app.service.ts
  WebApp/src/app/services/global.service.ts
  WebApp/src/assets/promos/PromoImage1.jpg
  WebApp/src/assets/promos/PromoImage2.jpg
  WebApp/src/assets/promos/PromoImage3.jpg
  WebApp/src/assets/promos/PromoImage4.png
  WebApp/src/assets/promos/PromoImage5.jpg
  WebApp/src/assets/promos/PromoImage6.jpg
  WebApp/src/assets/promos/PromoImage7.jpg
  WebApp/src/styles.scss
Labels: enhancement, Sprint1

#35 Fetch the required genres based on the GET request
  backend/controller/getGenres.go
  backend/controller/route.go
  backend/main.go
Labels: enhancement, Sprint1, Feature

#38 GenreBooks Page creation and redirection
  WebApp/src/app/app-routing.module.ts
  WebApp/src/app/app.module.ts
  WebApp/src/app/common-menu/common-menu.component.html
  WebApp/src/app/common-menu/common-menu.component.ts
  WebApp/src/app/genre-books/genre-books.component.html
  WebApp/src/app/genre-books/genre-books.component.scss
  WebApp/src/app/genre-books/genre-books.component.spec.ts
  WebApp/src/app/genre-books/genre-books.component.ts
  WebApp/src/app/services/api.service.ts
Labels: Sprint1, Feature

#63 Manish
  WebApp/src/app/homepage/homepage.component.html
  backend/databases/books.db
Labels: bug, Sprint1-Bugs, Sprint2

#67 Login Page Modification
  WebApp/src/app/app.module.ts
  WebApp/src/app/login/login.component.html
  WebApp/src/app/login/login.component.scss
  WebApp/src/app/login/login.component.ts
Labels: enhancement, Sprint 1 - Enhancement, Sprint2
